# Generated by Django 4.2.2 on 2023-07-22 11:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assignee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.usermodel')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='task.taskmodel')),
            ],
        ),
        migrations.AddField(
            model_name='taskmodel',
            name='assignees',
            field=models.ManyToManyField(related_name='tasks_assigned', through='task.Assignment', to='user.usermodel'),
        ),
    ]
